### ISSUE TITLE
Compile error in Opencv

### ISSUE THREAD

**Issue by zmwhit** [HKUST-Aerial-Robotics/EPSILON#10]
platform : ubuntu18.04
When compiling whole project you may find that

libhkust_pl_smm.so：对‘cv::fillPoly(cv::_InputOutputArray const&, cv::_InputArray const&, cv::Scalar_<double> const&, int, int, cv::Point_<int>)’未定义的引用

**Comment by zmwhit** [comment]
A feasible solution :
Add opencv dependency in package "semantic_map_manager"

find_package(OpenCV REQUIRED)
include_directories(
  ...
  ${OpenCV_INCLUDE_DIRS}
)
target_link_libraries(
 ...
 ${OpenCV_LIBS} 
)

**Comment by pch9520** [comment]
> A feasible solution : Add opencv dependency in package "semantic_map_manager"
> 
> find_package(OpenCV REQUIRED) include_directories( ... ${OpenCV_INCLUDE_DIRS} ) target_link_libraries( ... ${OpenCV_LIBS} )

Helpful!

**Comment by MasterIzumi** [comment]
@zmwhit Thx. This issue has been fixed.
