### ISSUE TITLE
problem of simulate the ego car

### ISSUE THREAD

**Issue by ZOUYIyi** [HKUST-Aerial-Robotics/EPSILON#11]
I read the code to find  when  simulate the ego car in one policy in function  **EgoAgentForwardSim** ,and it uses the function  **PropagateOnceAdvancedLK**,it seems like that it ignores the ego.lon_behavior ,then just one step forward with some caculated velocity.

**Comment by MasterIzumi** [comment]
@ZOUYIyi  In our implementation, the longitudinal behaviors are realized using different parameter sets of the longitudinal controller (i.e., IDM controller).
In UpdateSimSetupForScenario, for each action (e.g., DcpLonAction::kAccelerate), we determine a set of IDM parameters for the forward simulation. Different settings of the longitudinal controller can generate different simulated trajectories.

**Comment by ZOUYIyi** [comment]
@MasterIzumi 
thanks !  I find that ,  I will read it more carefully...

**Comment by ZOUYIyi** [comment]
I read the code for simulate the npc cars , it looks like that they just go along with the ref_lane ,and the  property : lat_probs  is not used. so how can we use the uncertainty of this lat_probs

**Comment by MasterIzumi** [comment]
@ZOUYIyi Hi, sorry, the released implementation is not complete yet. As stated in the paper, the 'Guided Observation Branching' part handles the intention prediction uncertainty, and these functions will be realized in SimulateActionSequence. It will firstly conduct a preliminary safety assessment and generate several risky 'scenarios', then launch multiple 'sub-threads' for forward simulations. Currently, the released version only considers the 'most likely scenario', i.e., only one scenario for each action sequence. We will clean the code and release these parts in the future.

**Comment by ZOUYIyi** [comment]
@MasterIzumi Thanks still . Is the core/behaivor_planner a complete work for MPDM algorithm ? Because it seems like a substitute for eudm algorithm. If it is complete , it is still a good choice.

**Comment by MasterIzumi** [comment]
@ZOUYIyi Yes, this is our implementation of the basic version of MPDM (from the paper - MPDM: Multipolicy decision-making in dynamic, uncertain environments for autonomous driving), which also uses the most likely intentions in the forward simulation. The full version of MPDM (Multipolicy decision-making for autonomous driving via changepoint-based behavior prediction: Theory and experiment) that contains a changepoint-based prediction is not involved in this package.

**Comment by ZOUYIyi** [comment]
@MasterIzumi  Thanks for your replay
