### ISSUE TITLE
How to access the neural network module?

### ISSUE THREAD

**Issue by cugbbaiyun** [HKUST-Aerial-Robotics/EPSILON#18]
Hi, I read the code but i can hardly find the definitions of neural network modules (encoder and decoder in intention estimator) and the parameters. It seems that the neural network modules are not included in encoder.h and decoder.h. 
And is it possible to change the structure of encoders or decoders?
Besides, how to train my own decoders and encoders?

**Comment by MasterIzumi** [comment]
Unfortunately, the learning-based intention estimation part is not available in the released repo. Actually, it is a pretty simple network compared to the current prediction SOTAs (of course there's a quite big performance gap as well). If you really need this part, we can provide you with a sample code only for the learning-based intention prediction module.
(Have responded via email)

**Comment by haotruongnhat** [comment]
Hi authors, could I have the code of learning-based intention prediction module for reference. Thank a lot!
Regards,

**Comment by feiyuxiaoThu** [comment]
> Unfortunately, the learning-based intention estimation part is not available in the released repo. Actually, it is a pretty simple network compared to the current prediction SOTAs (of course there's a quite big performance gap as well). If you really need this part, we can provide you with a sample code only for the learning-based intention prediction module. (Have responded via email)

We recently want to evaluate the performance of the distilled-Bi-LSTM network (from some transformer network), and could you provide your basic network so we can use for baseline. Thanks a lot for your reply.

**Comment by MasterIzumi** [comment]
@feiyuxiaoThu Actually, it is a quite simple intention classification network and already out-of-date at this time point. If you are working on the motion or trajectory prediction task, you can refer to our recent work which is more modern and effective.
Project page: https://github.com/HKUST-Aerial-Robotics/SIMPL

**Comment by feiyuxiaoThu** [comment]
> @feiyuxiaoThu Actually, it is a quite simple intention classification network and already out-of-date at this time point. If you are working on the motion or trajectory prediction task, you can refer to our recent work which is more modern and effective. Project page: https://github.com/HKUST-Aerial-Robotics/SIMPL

Thanks for your reply, and we will refer to your mentioned work.

**Comment by wlsdaydayup** [comment]
Hi authors, could I have the code of learning-based intention prediction module of EPSILON for reference. Thank a lot!
Regards,
Myemail:sduwls@163.com

**Comment by iloveai8086** [comment]
Thank you for the great work! I'm still eager to learn more about the model part. You can reach me at: 54228619@qq.com.
