### ISSUE TITLE
where is the navi_path in eudm

### ISSUE THREAD

**Issue by xunkaixin** [HKUST-Aerial-Robotics/EPSILON#28]
i can not find navi_path in eudm, the para of GetRefLaneForStateByBehavior always "std::vector<int>()"

**Comment by fanyu2021** [comment]
I can't understand your meaning. Give an example please!

**Comment by fanyu2021** [comment]
> i can not find navi_path in eudm, the para of GetRefLaneForStateByBehavior always "std::vector()"

I can't understand your meaning. Give an example please!

**Comment by fanyu2021** [comment]
> i can not find navi_path in eudm, the para of GetRefLaneForStateByBehavior always "std::vector()"

I can't understand your meaning. Give an example please!

**Comment by xunkaixin** [comment]
1. example:
in eudm_planner.cc, 	
"if (map_itf_->GetEgoLaneIdByPosition(std::vector<int>(),
		&ego_lane_id_by_pos) != kSuccess)" 
		
2. in function of “GetNearestLaneIdUsingState”, the para "navi_path" doesn't seem to be working
		
		
3. i just want to pass the global path into EUDM to determine the driving path,  Or other ways to pass in the global path

can you give me some advice

**Comment by fanyu2021** [comment]
> 1. example:
>    in eudm_planner.cc,
>    "if (map_itf_->GetEgoLaneIdByPosition(std::vector(),
>    &ego_lane_id_by_pos) != kSuccess)"
> 2. in function of “GetNearestLaneIdUsingState”, the para "navi_path" doesn't seem to be working
> 3. i just want to pass the global path into EUDM to determine the driving path,  Or other ways to pass in the global path
> 
> can you give me some advice

1.construct navi_path data struct, and give it to this function;
2.caculate the nearest path by distance just as the given code;

**Comment by xunkaixin** [comment]
i have look into and test the code, i find the ego car run random way. it can change lane, but not run along the global pah.  once  cross road, the ego car may run straight or turn left or right
