### ISSUE TITLE
How to simulate the occuslion of perception

### ISSUE THREAD

**Issue by KailinTong** [HKUST-Aerial-Robotics/EPSILON#5]
Dear author,

In the video you simulated the occuslion of perception, like the picture below. It looks really nice.
Could you please give me some hints on how to implement this in ROS and tell me the corresponding code?
![image](https://user-images.githubusercontent.com/39188064/129744220-2c541917-d456-4505-a8e8-d3efce610004.png)

Thanks a lot!
image

**Comment by MasterIzumi** [comment]
@KailinTong Hi, this is based on 2D ray casting on a grid map, and the implementation is based on [this repo](https://gist.github.com/zloedi/9551625). You can also find the code in `core/semantic_map_manager/thirdparty/roguelike_ray_casting/`.

**Comment by KailinTong** [comment]
Thank you very much!
