### ISSUE TITLE
build a demo

### ISSUE THREAD

**Issue by ZOUYIyi** [HKUST-Aerial-Robotics/EPSILON#6]
How can I use this repo to build a demo ? 
Is there any tutorial or something like it ?

**Comment by MasterIzumi** [comment]
@ZOUYIyi 
Sorry for the delay of the related documents. We will release a detailed instruction within Sept. :)

**Comment by ZOUYIyi** [comment]
@MasterIzumi 
Thank you so much for all you have done :/)

**Comment by MasterIzumi** [comment]
@ZOUYIyi 
Hi, we have added an installation guide. Please update the code and re-build it according to the instruction.
Please let me know if you meet any problems, especially dependency issues.

**Comment by ZOUYIyi** [comment]
@MasterIzumi 
Thank you ! I have already done before , it works  well !
