### ISSUE TITLE
What is the interactive multi-agent simulation platform proposed in this paper? 

### ISSUE THREAD

**Issue by Highlight123** [HKUST-Aerial-Robotics/EPSILON#8]
What is the interactive multi-agent simulation platform proposed in this paper?

**Comment by MasterIzumi** [comment]
@Highlight123 
Hi, we have added an installation guide, you can follow the instructions and try the demo.

The simulator is based on ROS and the implementation is quite simple, you can refer to the code for details (package phy_simulator). Intuitively, the simulator's node maintains the state of all agents and broadcast the information to all agents' nodes. Then, the agent's node calculates a control signal and pass it back to the simulator's node for state update.

Currently, the function of the simulator is simple. We are planning to refactor it and add more features. :)
